package examples.example;

// if it's implementing it's an interface
// implementing ... cloning
//Runtime?
//Compile time?

//Compile-time and runtime are two programming terms used in development
//compile-time is the time when the code is converting to an executable code into byte code
//while runtime is the time which the execution of the code has started.

//Compile time Errors??
//Syntax error->when the programmer makes an error in writing the code
//Semantic Error-> when the code is not meaningful to the compiler

//Runtime Error?
//runtime errors are the errors that occur not generated by compiler and could produce unpredictable
//result at execution of code
//compiler does not detect the error so it cannot prevent code from execution.
//error occurs during the execution of the code are runtime errors
//E.G., sqroot of a - number of dividing a number by 0

public class ObjectCloning {
    public static void main(String[] args) {
        try {
            Student s1 = new Student(1,"Brian");
            Student s2 = new Student(2,"Kim");
            Student s3 = new Student(3,"Patrick");

            Student s5 = (Student)s2.clone();
            Student s6 = (Student)s3.clone();
            Student s4 = (Student)s1.clone();// will not take up space or memory

            System.out.println(s1.id+" "+s1.name);
            System.out.println(s2.id+" "+s2.name);
            System.out.println(s3.id+" "+s3.name);
            System.out.println();
            System.out.println(s4.id+" "+s4.name);
            System.out.println(s5.id+" "+s5.name);
            System.out.println(s6.id+" "+s6.name);

        }catch (CloneNotSupportedException e){ // corrects run time errors
            System.out.println(e);
        }

    }
}

class Student implements Cloneable{
    int id;
    String name;
    public Student(int id, String name){
        this.id = id;
        this.name = name;
    }

    public Object clone()throws CloneNotSupportedException{ // e is the name of the clone variable
        return super.clone();
    }


}


